---
# tasks file for nginx

 - name: nginx installing
   yum:
      name: nginx
      state: present
 - name: port changing and mone jinja file
   template:
      src: default.conf.j2
      dest: /etc/nginx/conf.d/default.conf 
   notify: 
   - restart nginx       
